---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test2app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: mas
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/tomklapiscak/argocdtest
    path: applications/test
    targetRevision: "main"
    helm:
      parameters:
        - name: "i"
          value: "2"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - RespectIgnoreDifferences=true
