---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test1appset
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - "i": "1"
  template:
    metadata:
      name: "test{{`{{.i}}`}}app"
      annotations:
        argocd.argoproj.io/sync-wave: "{{`{{.i}}`}}"
    spec:
      project: mas
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      source:
        repoURL: https://github.com/tomklapiscak/argocdtest
        path: applications/test
        targetRevision: "main"
        helm:
          parameters:
            - name: "i"
              value: "{{ `{{.i}}`  }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
          - RespectIgnoreDifferences=true
